theme: minima
title: 	My Blog
author: Dang-Khanh Nguyen
description: It takes a hundred times to learn, a thousand times to understand
social-network-links:
  email: "khanhnd185@gmail.com"
  github: khanhnd185
  linkedin: khanh-nguyen-abcdef13
